language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "eJ0i/ME3loJ+uHKz7ycioeKMvcROHrRYbsUZRBTFLB6eHPMjtoa2/zjcgd442OkWtRtvECqSfA6/R2q4IZfSbzMlL+vHZE7RnB6Qtz8q1w8ZHxTyJsw1U72OuC/xMBYxs/M1T/cB6YT5tOTOGlPQqVliQfwp1AIIMWNlGw9wcu68KZvPS6B/Rg3x/Lf8yshyQZA9XnaN/NCUu8V3PXr6yuKppLWNsc5sqiL2qxsQFi/CElXknS9qM9JloRc8ssi3NEeLIybJHwAxmZ7rHCXzYyPWgTtWzeTKNrxCA9fo03sInY8AmlT1rXF8RgrnUp5dheFKeQF+g6DMIXjYIx8X7C6VLW2aRj7Bbqeiv2G/JEwW/1txMbTGU6DD0QMhYsO5oj/Z989kEdpb1HGOKAdFkYK8o+WmvfyqJLfDK6f4fHPNg3IxnL7lubKbevtfmor7vYX/w950Ey2loTb789rFRQ0tMH2pz6ZbK7W4LOM44ES/n4y+Y8IqA38VxXoGRYKTRX6X1Jcf1r2jnb+FCqIiUgjiHJTy3m13QAHXCd3HakRaZGRLtJpjfwMEH9ag7/Y8ErHobSa7vcu3YNYZ5i1c0BLgdHHgrUykiJCPymzGC7tT80oXPvxMjL9ZK6f7M5MaMJWzqLEK5JDsMUwT/gsltbkjDG7y4cgpf67zkJeGgD4="
    - secure: "jizoMmbo/c2zajiPnKyAxthJ+fRGqm4MyDPBJ10MFSw7wB4YISdNis+iaMukQJclAeDeGv2gl2k9lbm78WU7pRAd9epg4+E+AjgDGShRJIq5SF0i0FZJ55T43KT9+eTtNy9chM3fqDJng+/Anqy9WH9Kevogm1u/Wi6VsTsEjdtVBCKF02DASaasrQkFYFTaKER//ilKeXBIEMizdpQ0ZQ9ZMzf8/QsopCcm/c5J5Y6gDfziGKYXz1UDDrumaWeggaM8RxkSFti13KDMQfGYfbxAT6HcPHQmsAWSLKr5eEpQeFWDgI8RWtl5Anp8lSFCAcEaqSLIuAa7ewswaz5cTbTmYpId0bSTMznnbza913eeCjnpjLW+zrtYHecAJ/g/G4ew9/MKA/7VmJI4FCZh9wkX1QQPWMg9lLp0Y4eMbceTU/+xravFdv27jdhZzGSIRLWMXD228TWVXVkoSOKTlelQPXHFtAe2vN91TeWcH6uzFSxH3rwZkW8sK7vsu0pVgajZuhUJ7g+zzH6oIEdVcm6fFgVw6kMkoxXsUMb7dl1h1bTAkcYbPjkYqaSgnkz9GvcaG+QdxpkmixgzgzMtlE7RyoE7rmGGlD6YulaPS7+UP2VcYkobLGvnSbe6j9Qoh7HQODrQf58TDrZLH4VKLiQY95NWTnPx5+CloIrAe30="

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
